version: "3"

services:
    postgres:
        image: postgis/postgis:latest
        ports:
        - "5432:5432"
        volumes:
            - ./dbs/postgres-data:/var/lib/postgresql
        env_file:
            - ./.env

    redis:
        image: redis:alpine
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./dbs/redis-data:/data/
